#!/bin/sh -e

# Based on: https://github.com/aria2/aria2/blob/master/mingw-config
# This is the configure script wrapper for cross-compiling MinGW32
# build on Debian Linux using mingw-w64. Some environment variables
# can be adjusted to change build settings:
#
# HOST: cross-compile to build programs to run on HOST. It defaults to
#       i686-w64-mingw32. To build 64 bit binary, specify
#       x86_64-w64-mingw32.
#
# PREFIX: Prefix to the directory where dependent libraries are
#       installed.  It defaults to /usr/local/$HOST. -I$PREFIX/include
#       will be added to CPPFLAGS. -L$PREFIX/lib will be added to
#       LDFLAGS. $PREFIX/lib/pkgconfig will be set to
#       PKG_CONFIG_LIBDIR.
#
# In this configuration, the following dependent libraries are used:
#
# * c-ares
# * gmp
# * expat
# * sqlite3
# * zlib
# * libssh2
# * cppunit

test -z "$HOST" && HOST=i686-w64-mingw32
test -z "$PREFIX" && PREFIX=/usr/local/$HOST

./configure \
    --host=$HOST \
    --prefix=$PREFIX \
    --without-included-gettext \
    --disable-nls \
    --with-libcares \
    --without-gnutls \
    --without-wintls \
    --with-openssl \
    --with-sqlite3 \
    --without-libxml2 \
    --with-libexpat \
    --with-libz \
    --with-libssh2 \
    --without-libgcrypt \
    --without-libnettle \
    --with-cppunit-prefix=$PREFIX \
    ARIA2_STATIC=yes \
    CPPFLAGS="-I$PREFIX/include" \
    LDFLAGS="-L$PREFIX/lib" \
    PKG_CONFIG="/usr/bin/pkg-config" \
    PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"
